{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mainli.plugin",
    "module": "analyze-so",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "analyze-so-1.0.0-SNAPSHOT.jar",
          "url": "analyze-so-1.0.0-SNAPSHOT.jar",
          "size": 9771,
          "sha512": "7d7ca5e628fca25544b021f28b3c0b3872c9fdfc66cd47fb21b0b179c0da9cd3f1705b80e69515b16a39ddc3916362554acfe8ac72717598e06d936f3341d410",
          "sha256": "1e5f3e67aa6f3efedcdfd4fc330d10cbfe4cf6694ae0111c84ceed0631840c6a",
          "sha1": "86404e92467c299c959707eda8aad0bc4855e304",
          "md5": "05706e9ebaf4eddfc687bde2fa3faf9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "analyze-so-1.0.0-SNAPSHOT.jar",
          "url": "analyze-so-1.0.0-SNAPSHOT.jar",
          "size": 9771,
          "sha512": "7d7ca5e628fca25544b021f28b3c0b3872c9fdfc66cd47fb21b0b179c0da9cd3f1705b80e69515b16a39ddc3916362554acfe8ac72717598e06d936f3341d410",
          "sha256": "1e5f3e67aa6f3efedcdfd4fc330d10cbfe4cf6694ae0111c84ceed0631840c6a",
          "sha1": "86404e92467c299c959707eda8aad0bc4855e304",
          "md5": "05706e9ebaf4eddfc687bde2fa3faf9b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "analyze-so-1.0.0-SNAPSHOT-javadoc.jar",
          "url": "analyze-so-1.0.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "31d8bf6e563941867d19b4735e0404c22a684ec7516dddbf1d114397215b6bc4db32197c4b9d305b452be67373fb7cb4895f0e69e0e4a617714d2de03ad6cff8",
          "sha256": "0777699660789821e1ce12123adbc818079711145f4c54562d20e74e6ce69b42",
          "sha1": "e1aace940aaa6756ee655024acfccbecb35febd5",
          "md5": "27003295f663c462dfa06269988570b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "analyze-so-1.0.0-SNAPSHOT-sources.jar",
          "url": "analyze-so-1.0.0-SNAPSHOT-sources.jar",
          "size": 2328,
          "sha512": "6a8d25ff81e33e73605dee5f34e0713d00955a9b13ef0b1af19673e1a2952eb978fc40789882647e3d5253f0237308c90147a7fb9799c6d49e80632cfed33763",
          "sha256": "a05b9cdd09d7c3f0196697fd4712174a34a8f68d2ffe5fe9e5284ae048e73f57",
          "sha1": "cea95110a7930e9624fdb88ab7088b9cece4477d",
          "md5": "87671c430c650cea72904e1f052246d1"
        }
      ]
    }
  ]
}
