{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Android-Mainli",
    "module": "AnalyzeSoPlugin",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "AnalyzeSoPlugin-1.0.2.jar",
          "url": "AnalyzeSoPlugin-1.0.2.jar",
          "size": 10003,
          "sha512": "6c6fa20f50384460bdd5cc8ff70c23b19b8d692e7a162e943776e2a86d9378e278696b80e8eec9516b2269f095f45c125d41418dd7ba33ebf71b94898584e330",
          "sha256": "44092a354cc8daedb91bac648917d95cafd129edbe26705a2549cc4d97d110fc",
          "sha1": "aeea1efd6315c035462dd7c55990b2e542266fe7",
          "md5": "7bf8a5cf7daf1ee1b1db119fc0637fc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "AnalyzeSoPlugin-1.0.2.jar",
          "url": "AnalyzeSoPlugin-1.0.2.jar",
          "size": 10003,
          "sha512": "6c6fa20f50384460bdd5cc8ff70c23b19b8d692e7a162e943776e2a86d9378e278696b80e8eec9516b2269f095f45c125d41418dd7ba33ebf71b94898584e330",
          "sha256": "44092a354cc8daedb91bac648917d95cafd129edbe26705a2549cc4d97d110fc",
          "sha1": "aeea1efd6315c035462dd7c55990b2e542266fe7",
          "md5": "7bf8a5cf7daf1ee1b1db119fc0637fc4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AnalyzeSoPlugin-1.0.2-javadoc.jar",
          "url": "AnalyzeSoPlugin-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "ef3ab37c3cda5472503ceea100e4c399630cbbf46b3ce735bdfc15c49a0d1eb0d85a8184cd93fb30f1d377f348807e2c5ee6930bae252f5ffc8e8e81b8850916",
          "sha256": "a7985d2dc4d5a3721ef9b00e72d21904e2503021e65eb90ae95b4e136341ece9",
          "sha1": "c819718a3556c6d72ad757c652f0a1bb0baa233b",
          "md5": "ad1805e9e12bae1a03f503817a0ece22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AnalyzeSoPlugin-1.0.2-sources.jar",
          "url": "AnalyzeSoPlugin-1.0.2-sources.jar",
          "size": 2368,
          "sha512": "0caf05fb7fd0dc734af5051aa1fdc9fdbe71db3e7abbe5b9687ac5f2631084b4c4b1c0b5a98d9905998b72241cf1386d52377bd138b500dcc32454dec1d8bbc2",
          "sha256": "4cfbb0604e55ca98c001258ae2dd9c9e8c0a739e2fe50f0e52f2aa935c0c3cbe",
          "sha1": "68b250d4bf50ec7dd9ee09a10250bebf20be58a3",
          "md5": "20dc7560c573125ed76b055f1a9d0cff"
        }
      ]
    }
  ]
}
