{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Android-Mainli",
    "module": "AnalyzeSoPlugin",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "AnalyzeSoPlugin-1.0.2.jar",
          "url": "AnalyzeSoPlugin-1.0.2.jar",
          "size": 9827,
          "sha512": "440a0dc827aa1f191fbb973f6d6b8d84635e7b2158215987258079516062bbabecd861d7248278419e59f1f9f7db0b9ab1b1b2f3382afb71effc8b717503caa7",
          "sha256": "77eb1d8805ef396675d666ac5fd7b9754493e8436416381463d4f746b4dc1c4f",
          "sha1": "a1b6e55ff2b11a12e436860a9a8865b2906ef0f2",
          "md5": "c4ab3c089a4c93ff975f8e4fefef22a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "AnalyzeSoPlugin-1.0.2.jar",
          "url": "AnalyzeSoPlugin-1.0.2.jar",
          "size": 9827,
          "sha512": "440a0dc827aa1f191fbb973f6d6b8d84635e7b2158215987258079516062bbabecd861d7248278419e59f1f9f7db0b9ab1b1b2f3382afb71effc8b717503caa7",
          "sha256": "77eb1d8805ef396675d666ac5fd7b9754493e8436416381463d4f746b4dc1c4f",
          "sha1": "a1b6e55ff2b11a12e436860a9a8865b2906ef0f2",
          "md5": "c4ab3c089a4c93ff975f8e4fefef22a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AnalyzeSoPlugin-1.0.2-javadoc.jar",
          "url": "AnalyzeSoPlugin-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "ef3ab37c3cda5472503ceea100e4c399630cbbf46b3ce735bdfc15c49a0d1eb0d85a8184cd93fb30f1d377f348807e2c5ee6930bae252f5ffc8e8e81b8850916",
          "sha256": "a7985d2dc4d5a3721ef9b00e72d21904e2503021e65eb90ae95b4e136341ece9",
          "sha1": "c819718a3556c6d72ad757c652f0a1bb0baa233b",
          "md5": "ad1805e9e12bae1a03f503817a0ece22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AnalyzeSoPlugin-1.0.2-sources.jar",
          "url": "AnalyzeSoPlugin-1.0.2-sources.jar",
          "size": 2355,
          "sha512": "3821719991b85c7b1dd44d51c45b4bf7a3fb5c99f9c0874ed1456b18530f9eb00cfa64d6918c3ccfb0fc51fb8ffd716ba225d6417058d3c974bfd9219a854397",
          "sha256": "9938c33ae3b3e9f18a0ad03a88f1f902d28bb4cd28706704ea5e7f37447b841c",
          "sha1": "c666660f191f97fde18b1f19bf09013e57e8ea32",
          "md5": "1fb7d13cd692053043bf107654b6332d"
        }
      ]
    }
  ]
}
